# app
app:
  name: 

# 服务器
server:
  port: 8088

# MySQL
mysql:
  username: root
  password: 
  dsn: tcp(localhost:3306)/pApp?charset=utf8&parseTime=True&loc=Local

# Redis
redis:
  addr: localhost:6379

# token
jwt:
  signedKey: abcdefghijk
  maxAge: 86400

# mail
mail:
  host: smtp.qq.com
  port: 465
  username: 
  alias: 
  password: 
  closeTime: 10

# 微信
wx:
  appid: 
  secret: 