# 服务器
server:
  port: 8088

# MySQL
mysql:
  username: root
  password: 19971119
  dsn: tcp(localhost:3306)/pApp?charset=utf8&parseTime=True&loc=Local

# Redis
redis:
  addr: localhost:6379

# token
jwt:
  signedKey: abcdefghijk
  maxAge: 86400
